apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/component: webhook-mw-job
  name: webhook-mw-job
spec:
  template:
    metadata:
      name: webhook-mw-job
    spec:
      containers:
      - command:
        - sh
        - -c
        - |
          set -e
          K8S_NAMESPACE=default
          CA_BUNDLE=$(kubectl get configmap -n kube-system extension-apiserver-authentication -o=jsonpath='{.data.client-ca-file}' | base64 | tr -d '\n')

          if [ ! $CA_BUNDLE ]; then
              echo "ERROR: CA_BUNDLE is empty!" >&2
              exit 1
          fi

          cat <<EOF | kubectl -n ${K8S_NAMESPACE} apply -f -
          apiVersion: admissionregistration.k8s.io/v1beta1
          kind: MutatingWebhookConfiguration
          metadata:
            name: chaos-mesh-sidecar-injector
          webhooks:
            - name: admission-webhook.pingcap.com
              clientConfig:
                caBundle: "${CA_BUNDLE}"
                service:
                  name: chaos-mesh-controller-manager
                  namespace: default
                  path: "/inject-v1-pod"
            - name: mpodchaos.kb.io
              clientConfig:
                caBundle: "${CA_BUNDLE}"
                service:
                  name: chaos-mesh-controller-manager
                  namespace: default
                  path: /mutate-pingcap-com-v1alpha1-podchaos
            - name: miochaos.kb.io
              clientConfig:
                caBundle: "${CA_BUNDLE}"
                service:
                  name: chaos-mesh-controller-manager
                  namespace: default
                  path: /mutate-pingcap-com-v1alpha1-iochaos
            - name: mtimechaos.kb.io
              clientConfig:
                caBundle: "${CA_BUNDLE}"
                service:
                  name: chaos-mesh-controller-manager
                  namespace: default
                  path: /mutate-pingcap-com-v1alpha1-timechaos
            - name: mnetworkchaos.kb.io
              clientConfig:
                caBundle: "${CA_BUNDLE}"
                service:
                  name: chaos-mesh-controller-manager
                  namespace: default
                  path: /mutate-pingcap-com-v1alpha1-networkchaos
            - name: mkernelchaos.kb.io
              clientConfig:
                caBundle: "${CA_BUNDLE}"
                service:
                  name: chaos-mesh-controller-manager
                  namespace: default
                  path: /mutate-pingcap-com-v1alpha1-kernelchaos
          ---
          apiVersion: admissionregistration.k8s.io/v1beta1
          kind: ValidatingWebhookConfiguration
          metadata:
            name: chaos-mesh-validation
          webhooks:
            - name: vpodchaos.kb.io
              clientConfig:
                caBundle: "${CA_BUNDLE}"
                service:
                  name: chaos-mesh-controller-manager
                  namespace: default
                  path: /validate-pingcap-com-v1alpha1-podchaos
            - name: viochaos.kb.io
              clientConfig:
                caBundle: "${CA_BUNDLE}"
                service:
                  name: chaos-mesh-controller-manager
                  namespace: default
                  path: /validate-pingcap-com-v1alpha1-iochaos
            - name: vtimechaos.kb.io
              clientConfig:
                caBundle: "${CA_BUNDLE}"
                service:
                  name: chaos-mesh-controller-manager
                  namespace: default
                  path: /validate-pingcap-com-v1alpha1-timechaos
            - name: vnetworkchaos.kb.io
              clientConfig:
                caBundle: "${CA_BUNDLE}"
                service:
                  name: chaos-mesh-controller-manager
                  namespace: default
                  path: /validate-pingcap-com-v1alpha1-networkchaos
            - name: vkernelchaos.kb.io
              clientConfig:
                caBundle: "${CA_BUNDLE}"
                service:
                  name: chaos-mesh-controller-manager
                  namespace: default
                  path: /validate-pingcap-com-v1alpha1-kernelchaos
          EOF
        image: bitnami/kubectl:latest
        imagePullPolicy: IfNotPresent
        name: chaos-mesh-job-mw
      restartPolicy: Never
      serviceAccountName: chaos-controller-manager
